[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['echo "Ensuring data files are present..." && ls -la backend/data/']

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production' 